package controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class OptionsController {
	@FXML
	private TextField usernameTextField;
	@FXML
	private TextField passwordTextField;
	@FXML
	private Button createAccountButton;
	@FXML
	private Button cancelButton;

	// Event Listener on Button[#createAccountButton].onAction
	@FXML
	public void createAccountButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#cancelButton].onAction
	@FXML
	public void cancelButtonOnAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
